[package]
name = "kvs"
version = "0.1.0"
authors = ["Paul Meng <me@paulme.ng>"]
edition = "2018"

[dependencies]
clap = {version = "2.33.0", features = ["yaml"]}

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
